---
- name: clone asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    version: v0.7.2
    dest: /opt/asdf
    force: yes

- name: make asdf executable by all
  file:
    mode: "777"
    path: /opt/asdf
    recurse: yes
    state: directory

- name: add asdf to bashrc
  lineinfile:
    path: /home/deploy/.bashrc
    line: "{{ item }}"
  with_items:
    - /opt/asdf/asdf.sh
    - /opt/asdf/completions/asdf.bash

- name: add elixir, erlang, node plugins
  command: /opt/asdf/bin/asdf plugin-add "{{ item }}"
  with_items:
    - java
    - erlang
    - elixir
    - nodejs

- name: install language versions
  command: /opt/asdf/bin/asdf install "{{ item }}"
  with_items:
    - "erlang 22.0"
    - "elixir 1.8.2"
    - "nodejs 10.15.3"

- name: set global versions
  command: /opt/asdf/bin/asdf global "{{ item }}"
  with_items:
    - "erlang 22.0"
    - "elixir 1.8.2"
    - "nodejs 10.15.3"
