---
- name: install hex & rebar
  command: "mix local.{{ item }} --force"
  args:
    chdir: /opt/app
  with_items:
    - hex
    - rebar

- name: install app dependencies
  command: "mix deps.get --force"
  args:
    chdir: /opt/app

- name: build release
  command: mix release
  args:
    chdir: /opt/app

- name: start release
  command: /opt/app/_build/prod/rel/deploy_elixir/bin/deploy_elixir start

- name: restart nginx
  systemd:
    name: nginx.service
    state: restarted

- name: bundle sqitch
  command: sqitch bundle
  args:
    chdir: /opt/app
