---
- name: create builds directory
  file:
    path: "/home/deploy/builds"
    state: directory
    owner: deploy

- name: create migrations directory
  file:
    path: "/home/deploy/migrations"
    state: directory
    owner: deploy

- name: send build to gcp, when the version is bumped
  synchronize:
    src: "../_build/prod"
    dest: "/home/deploy/builds/{{app_version}}"
    rsync_opts:
      - "--ignore-existing"

- name: send sqitch bundle to gcp, when the version is bumped
  synchronize:
    src: "../bundle"
    dest: "/home/deploy/migrations/{{app_version}}"
    rsync_opts:
      - "--ignore-existing"

- name: link latest build to users home
  file:
    state: link
    path:  "/home/deploy/current_build"
    src: "/home/deploy/builds/{{app_version}}"

- name: link latest migration to users home
  file:
    state: link
    path:  "/home/deploy/current_migration"
    src: "/home/deploy/migrations/{{app_version}}"
