---
- name: remove default nginx config
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default

- name: add nginx config
  template:
    src: ./nginx.j2
    dest: /etc/nginx/sites-available/tech-weights.com

- name: add nginx systed config
  template:
    src: ./nginx.service.j2
    dest: /lib/systemd/system/nginx.service

- name: restart nginx
  systemd:
    name: nginx.service
    state: restarted
